title: "CDteca from Configuration"
path: "/home/dados/cdteca"
verbose: True
ftp-port: 2020
ftp-user: ftpd
ftp-password: ftpass
checksum-method: sha512
html-theme: cyan
retains: 0
distros:
  - debian
  - fedora
  - ubuntu
  - mx