title: "CDteca from Configuration"
path: "/home/dados/cdteca"
verbose: True
ftp-port: 2020
ftp-user: ftpd
ftp-password: ftpass
checksum-method: sha512
html-theme: simple
retains: False
distros:
  - debian
  - ubuntu
  - mx
  - mint